apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prasanti-test
  labels:
    app.kubernetes.io/name: prasanti-test
    app.kubernetes.io/part-of: prasanti-test-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: prasanti-test